#!/usr/bin/env python3
"""
Build independent validation dataset: N-M NOAA events (no SAR) for testing
the ever-flooded map built from M events (with SAR).

Per city, cities are processed independently.
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

STUDY_YEAR_MIN = 2015
STUDY_YEAR_MAX = 2025

# SAR composite events used in GEE (for threshold-tuning train split within M)
GEE_SAR_EVENTS = {
    "houston": {
        "train": ["579534", "675235_and_1_more", "710731", "830461_and_1_more"],
        "map_all": [
            "579534", "675235_and_1_more", "710731", "710726_and_1_more",
            "721084_and_5_more", "830461_and_1_more", "857803_and_4_more",
            "899524", "963117", "1004355_and_4_more",
        ],
    },
    "raleigh": {
        "train": ["755610", "775029_and_1_more"],
        "map_all": [
            "755610", "775029_and_1_more", "1029187", "1173317", "1208432",
        ],
    },
}


def parse_event_date(date_str: str):
    from datetime import datetime

    for fmt in ("%m/%d/%Y", "%Y-%m-%d"):
        try:
            return datetime.strptime(date_str.strip(), fmt)
        except ValueError:
            continue
    return None


def in_study_period(date_str: str) -> bool:
    dt = parse_event_date(date_str)
    if dt is None:
        return False
    return STUDY_YEAR_MIN <= dt.year <= STUDY_YEAR_MAX


def load_noaa_points(city: str) -> list[dict]:
    path = ROOT / "data" / "raw" / city / "event_detection" / f"noaa_{city}_flood_events.csv"
    points: list[dict] = []
    with path.open() as f:
        for row in csv.DictReader(f):
            lat, lon = row.get("BEGIN_LAT", "").strip(), row.get("BEGIN_LON", "").strip()
            if not lat or not lon:
                continue
            try:
                lat_f, lon_f = float(lat), float(lon)
            except ValueError:
                continue
            points.append(
                {
                    "event_id": row["EVENT_ID"].strip(),
                    "event_date": row["BEGIN_DATE"].strip(),
                    "location": row.get("BEGIN_LOCATION", "").strip(),
                    "lat": lat_f,
                    "lon": lon_f,
                    "desc": f"{row.get('BEGIN_LOCATION', '')} ({row['BEGIN_DATE'].strip()})",
                }
            )
    return [p for p in points if in_study_period(p["event_date"])]


def sar_noaa_ids(city: str) -> set[str]:
    path = ROOT / "data" / "raw" / city / "event_detection" / "event_imagery_matches.csv"
    ids: set[str] = set()
    with path.open() as f:
        for row in csv.DictReader(f):
            for part in row.get("noaa_event_ids", "").split(";"):
                part = part.strip()
                if part:
                    ids.add(part)
    return ids


def build_city(city: str) -> dict:
    all_points = load_noaa_points(city)
    sar_ids = sar_noaa_ids(city)
    m_points = [p for p in all_points if p["event_id"] in sar_ids]
    nm_points = [p for p in all_points if p["event_id"] not in sar_ids]
    return {
        "city": city,
        "counts": {
            "noaa_with_coords": len(all_points),
            "m_sar_linked_noaa_points": len(m_points),
            "nm_independent_test_points": len(nm_points),
            "sar_composite_events_in_map": len(GEE_SAR_EVENTS[city]["map_all"]),
            "sar_composite_events_for_threshold_train": len(GEE_SAR_EVENTS[city]["train"]),
        },
        "sar_noaa_event_ids": sorted(sar_ids),
        "threshold_train_composite_ids": GEE_SAR_EVENTS[city]["train"],
        "map_composite_ids": GEE_SAR_EVENTS[city]["map_all"],
        "independent_test_points": nm_points,
        "m_noaa_points": m_points,
    }


def write_js_locations(city_data: dict, out_path: Path) -> None:
    lines = [
        "// Auto-generated by code/validation/build_independent_validation.py",
        "// N-M NOAA events (no SAR), study period 2015-2025: independent test points",
        "var independentValidationLocations = {",
    ]
    for city in ("raleigh", "houston"):
        pts = city_data[city]["independent_test_points"]
        lines.append(f'  {city}: [')
        for p in pts:
            desc = p["desc"].replace('"', '\\"')
            lines.append(
                f'    {{lat: {p["lat"]}, lon: {p["lon"]}, '
                f'eventId: "{p["event_id"]}", desc: "{desc}"}},'
            )
        lines.append("  ],")
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n")


def main() -> int:
    city_data = {city: build_city(city) for city in ("raleigh", "houston")}

    split = {
        "version": "2.1",
        "study_period": {"start_year": STUDY_YEAR_MIN, "end_year": STUDY_YEAR_MAX},
        "approach": "ever_flooded_map_with_independent_noaa_test",
        "description": (
            "Study period 2015-2025 (Sentinel-1 era). M events (SAR) build the ever-flooded map. "
            "N-M NOAA events (no SAR) provide independent test locations. "
            "Cities are independent."
        ),
        "locked_thresholds": {
            "vv_vh_threshold_db": -1.8,
            "vv_only_threshold_db": -2.0,
            "use_adaptive_threshold": False,
            "tuned_on": "train_subset_of_M_per_city",
            "tuned_using_noaa_from": "M_train_events_only",
        },
        "validation_metric": {
            "name": "buffered_detection_recall",
            "map_layer": "ever_flooded_union_of_all_M_events",
            "reference": "noaa_locations_from_N_minus_M_events",
            "buffers_m": [100, 250, 500, 1000],
            "generous": True,
        },
        "cities": city_data,
    }

    out_json = ROOT / "data" / "processed" / "validation_split.json"
    out_json.write_text(json.dumps(split, indent=2) + "\n")

    out_js = ROOT / "code" / "gee_mapping" / "independent_validation_locations.js"
    write_js_locations(city_data, out_js)

    gee_main = ROOT / "code" / "gee_mapping" / "generate_flood_hotspots.js"
    gee_bundle = ROOT / "code" / "gee_mapping" / "generate_flood_hotspots_gee_upload.js"
    gee_bundle.write_text(
        "// Single-file upload for Earth Engine (auto-generated — do not edit)\n"
        "// Regenerate: python3 code/validation/build_independent_validation.py\n\n"
        + out_js.read_text()
        + "\n"
        + gee_main.read_text()
    )

    print("Independent validation build (study period %d-%d)" % (STUDY_YEAR_MIN, STUDY_YEAR_MAX))
    print("=" * 60)
    for city in ("raleigh", "houston"):
        c = city_data[city]["counts"]
        print(f"{city.upper()}")
        print(f"  M (SAR-linked NOAA points):     {c['m_sar_linked_noaa_points']}")
        print(f"  N-M (independent test points):  {c['nm_independent_test_points']}")
        print(f"  SAR composites in map:          {c['sar_composite_events_in_map']}")
        print(f"  SAR composites for train/tune:  {c['sar_composite_events_for_threshold_train']}")
        print()
    print(f"Wrote {out_json}")
    print(f"Wrote {out_js}")
    print(f"Wrote {gee_bundle}  <- paste this ONE file into GEE")
    return 0


if __name__ == "__main__":
    sys.exit(main())
