// Single-file upload for Earth Engine (auto-generated — do not edit)
// Regenerate: python3 code/validation/build_independent_validation.py

// Auto-generated by code/validation/build_independent_validation.py
// N-M NOAA events (no SAR), study period 2015-2025: independent test points
var independentValidationLocations = {
  raleigh: [
    {lat: 35.7822, lon: -78.5941, eventId: "610222", desc: "WILDERS GROVE (12/30/2015)"},
    {lat: 35.8114, lon: -78.794, eventId: "653659", desc: "MORRISVILLE (07/16/2016)"},
    {lat: 35.8203, lon: -78.6393, eventId: "653729", desc: "RALEIGH (07/17/2016)"},
    {lat: 35.908, lon: -78.7933, eventId: "696352", desc: "(RDU)RALEIGH-DURHAM (04/25/2017)"},
    {lat: 35.83, lon: -78.76, eventId: "710139", desc: "(RDU)RALEIGH-DURHAM (06/16/2017)"},
    {lat: 35.77, lon: -78.69, eventId: "781161", desc: "COLLEGE VIEW (08/19/2018)"},
    {lat: 35.79, lon: -78.64, eventId: "781162", desc: "RALEIGH (08/19/2018)"},
    {lat: 35.86, lon: -78.64, eventId: "781163", desc: "MILLBROOK (08/19/2018)"},
    {lat: 35.8049, lon: -78.623, eventId: "781167", desc: "RALEIGH (08/20/2018)"},
    {lat: 35.87, lon: -78.58, eventId: "781168", desc: "FAWLERS XRDS (08/20/2018)"},
    {lat: 35.8, lon: -78.63, eventId: "781182", desc: "RALEIGH (08/20/2018)"},
    {lat: 35.76, lon: -78.64, eventId: "781183", desc: "ECHO HGTS (08/20/2018)"},
    {lat: 35.8209, lon: -78.6131, eventId: "820628", desc: "MILLBROOK (04/15/2019)"},
    {lat: 35.8, lon: -78.65, eventId: "874988", desc: "RALEIGH (02/06/2020)"},
    {lat: 35.7854, lon: -78.6369, eventId: "919574", desc: "RALEIGH (08/31/2020)"},
    {lat: 35.8439, lon: -78.6554, eventId: "922269", desc: "BROOKHAVEN (09/01/2020)"},
    {lat: 35.77, lon: -78.65, eventId: "1004729", desc: "CARALEIGH (01/03/2022)"},
    {lat: 35.7806, lon: -78.6434, eventId: "1013191", desc: "RALEIGH (03/17/2022)"},
    {lat: 35.7808, lon: -78.6754, eventId: "1028357", desc: "RALEIGH (05/07/2022)"},
    {lat: 35.62, lon: -78.89, eventId: "1029189", desc: "BURT (05/27/2022)"},
    {lat: 35.79, lon: -78.65, eventId: "1047668", desc: "RALEIGH (07/07/2022)"},
    {lat: 35.919, lon: -78.7893, eventId: "1047597", desc: "(RDU)RALEIGH-DURHAM (07/15/2022)"},
    {lat: 35.84, lon: -78.67, eventId: "1047599", desc: "BROOKHAVEN (07/15/2022)"},
    {lat: 35.85, lon: -78.71, eventId: "1047605", desc: "CAMP POLK (07/15/2022)"},
    {lat: 35.8, lon: -78.62, eventId: "1053676", desc: "RALEIGH (08/11/2022)"},
    {lat: 35.78, lon: -78.7, eventId: "1117393", desc: "COLLEGE VIEW (07/08/2023)"},
    {lat: 35.7919, lon: -78.6413, eventId: "1117420", desc: "RALEIGH (07/09/2023)"},
    {lat: 35.79, lon: -78.72, eventId: "1141263", desc: "WESTOVER (09/09/2023)"},
    {lat: 35.8652, lon: -78.7793, eventId: "1204072", desc: "(RDU)RALEIGH-DURHAM (07/18/2024)"},
    {lat: 35.791, lon: -78.6288, eventId: "1204074", desc: "RALEIGH (07/18/2024)"},
    {lat: 35.84, lon: -78.69, eventId: "1204127", desc: "CAMP POLK (07/25/2024)"},
    {lat: 35.8182, lon: -78.6143, eventId: "1209144", desc: "MILLBROOK (08/08/2024)"},
    {lat: 35.8058, lon: -78.6485, eventId: "1210464", desc: "RALEIGH (09/01/2024)"},
    {lat: 35.8822, lon: -78.7546, eventId: "1210467", desc: "(RDU)RALEIGH-DURHAM (09/01/2024)"},
    {lat: 35.8035, lon: -78.6201, eventId: "1216540", desc: "RALEIGH (09/27/2024)"},
    {lat: 35.85, lon: -78.59, eventId: "1245401", desc: "STARMOUNT (03/16/2025)"},
    {lat: 35.8, lon: -78.62, eventId: "1245402", desc: "RALEIGH (03/16/2025)"},
  ],
  houston: [
    {lat: 29.6949, lon: -95.2338, eventId: "561401", desc: "SOUTH HOUSTON (04/16/2015)"},
    {lat: 29.677, lon: -95.0118, eventId: "573365", desc: "LA PORTE (04/17/2015)"},
    {lat: 29.5269, lon: -95.0867, eventId: "579777", desc: "NASSAU BAY (05/25/2015)"},
    {lat: 29.9135, lon: -95.6411, eventId: "589615", desc: "HOUSTON WEISER ARPT (06/27/2015)"},
    {lat: 29.6499, lon: -95.1993, eventId: "589600", desc: "GENOA ARPT (06/30/2015)"},
    {lat: 29.8253, lon: -95.8447, eventId: "604967", desc: "KATY (10/24/2015)"},
    {lat: 29.9792, lon: -95.5426, eventId: "604968", desc: "ORR (10/31/2015)"},
    {lat: 29.7077, lon: -95.3876, eventId: "620705", desc: "HOUSTON (03/18/2016)"},
    {lat: 30.0825, lon: -95.5677, eventId: "644948", desc: "HOUSTON HOOKS ARPT (06/01/2016)"},
    {lat: 29.6627, lon: -95.2367, eventId: "687236", desc: "SOUTH HOUSTON (03/29/2017)"},
    {lat: 29.9191, lon: -95.6141, eventId: "714368", desc: "SATSUMA (07/09/2017)"},
    {lat: 30.1123, lon: -95.658, eventId: "720858", desc: "TOMBALL (08/26/2017)"},
    {lat: 29.9887, lon: -95.8392, eventId: "720860", desc: "HOCKLEY (08/26/2017)"},
    {lat: 29.5688, lon: -95.0139, eventId: "720861", desc: "JOYCE (08/26/2017)"},
    {lat: 29.8599, lon: -95.4273, eventId: "720867", desc: "ACRE HOMES (08/26/2017)"},
    {lat: 30.0886, lon: -95.993, eventId: "720869", desc: "HOCKLEY (08/26/2017)"},
    {lat: 29.7216, lon: -95.2927, eventId: "720873", desc: "CLINTON PARK (08/26/2017)"},
    {lat: 29.7438, lon: -95.3546, eventId: "714586", desc: "HOUSTON (09/18/2017)"},
    {lat: 29.5882, lon: -95.0944, eventId: "757732", desc: "TAYLOR LAKE VLG (07/03/2018)"},
    {lat: 30.1081, lon: -95.3535, eventId: "757973", desc: "SPRING (07/04/2018)"},
    {lat: 29.7624, lon: -95.3428, eventId: "797754", desc: "ENGLEWOOD (12/07/2018)"},
    {lat: 29.6631, lon: -95.5649, eventId: "797758", desc: "WEST PARK (12/08/2018)"},
    {lat: 29.5904, lon: -95.1057, eventId: "853617", desc: "WALLIS (08/23/2019)"},
    {lat: 29.6055, lon: -95.2776, eventId: "921900", desc: "EAST HAVEN (09/21/2020)"},
    {lat: 29.5958, lon: -95.3561, eventId: "922065", desc: "MINNETEX (09/21/2020)"},
    {lat: 29.89, lon: -95.32, eventId: "960082", desc: "KINGWOOD (05/18/2021)"},
    {lat: 29.7037, lon: -95.3712, eventId: "960135", desc: "HOUSTON (05/24/2021)"},
    {lat: 29.75, lon: -95.53, eventId: "966346", desc: "BUNKER HILL (08/16/2021)"},
    {lat: 29.9046, lon: -95.4707, eventId: "1102311", desc: "HOUSTON COLLIER ARPT (05/14/2023)"},
  ],
};

/**
 * Flood Hotspot Map Generator for Raleigh, NC and Houston, TX
 *
 * This script aggregates flood detections across all events for a city
 * to create a hotspot map showing where flooding occurs most frequently.
 *
 * VALIDATION: Use `generate_flood_hotspots_gee_upload.js` in Earth Engine (single file).
 * Regenerate: python3 code/validation/build_independent_validation.py
 * See docs/validation_independence.md.
 * 
 * Color scheme:
 * - Yellow: 1 event detected flooding
 * - Orange: 2-3 events detected flooding
 * - Red: 4+ events detected flooding
 * - Transparent: 0 events (no flooding detected)
 */

// ============================================================================
// USER SETTINGS
// ============================================================================

var selectedCity = 'raleigh'; // 'raleigh' or 'houston'

// Multi-image baseline: average multiple pre-event images for more stable baseline
// Set to true to enable averaging 3-5 pre-event images (reduces speckle noise)
// Set to false to use single closest pre-event image (current behavior, default)
var useMultiImageBaseline = false;
var multiImageDaysBefore = 30;  // Days before event to search for pre-event images
var multiImageMaxCount = 5;   // Maximum number of images to average

// Adaptive threshold: derive threshold from each scene instead of fixed dB
// MUST be false for held-out validation (see docs/validation_independence.md).
// Adaptive mode uses scene percentiles and leaks information from the evaluated event.
var useAdaptiveThreshold = false;

// ============================================================================
// FLOOD DETECTION PARAMETERS (SHARED WITH visualize_flood_events.js)
// ============================================================================
// IMPORTANT: These parameters must match visualize_flood_events.js exactly
// to ensure consistent flood detection across both scripts.

var FLOOD_DETECTION_CONFIG = {
  // Speckle filtering
  smoothRadius: 90,  // meters - radius for focal_mean smoothing
  
  // Change detection thresholds (dB) - used when useAdaptiveThreshold is false
  vvVhThreshold: -1.8,  // dB - threshold when both VV and VH are available
  vvOnlyThreshold: -2.0,  // dB - stricter threshold when only VV is available
  
  // Adaptive threshold (when useAdaptiveThreshold is true): percentile of VV change, clamped
  adaptivePercentile: 7,       // use this percentile of change image over AOI
  adaptiveThresholdMin: -2.8,   // clamp threshold to no more negative than this (dB)
  adaptiveThresholdMax: -1.0,   // clamp threshold to no less negative than this (dB)
  
  // Speckle removal
  minConnectedPixels: 5,  // minimum connected pixels to keep (removes isolated noise)
  connectedNeighborhood: 8,  // 8-connected neighborhood for pixel counting
  
  // Urban mask
  nlcdImperviousThreshold: 0.2,  // >=20% impervious surface
  worldCoverBuiltClass: 50,  // WorldCover built-up class value
  
  // Permanent water exclusion
  jrcWaterOccurrenceThreshold: 50  // >=50% occurrence = permanent water
};

// ============================================================================
// THRESHOLD TRAINING (subset of M / SAR events only) — docs/validation_independence.md
// Lock thresholds using these composite events per city before building the map.
// Independent test uses N-M NOAA points (no SAR), not these events.
// ============================================================================

var THRESHOLD_TRAIN_COMPOSITE_IDS = {
  houston: ['579534', '675235_and_1_more', '710731', '830461_and_1_more'],
  raleigh: ['755610', '775029_and_1_more']
};

// ============================================================================
// CITY CONFIGURATION
// ============================================================================

var cityConfig = {
  raleigh: {
    outerAOICoords: [
      [-78.9, 35.6],
      [-78.4, 35.6],
      [-78.4, 36.1],
      [-78.9, 36.1],
      [-78.9, 35.6]
    ],
    focusBuffer: -5000, // tighten AOI for visualization
    centerZoom: 13,
    floodLocations: {
      '755610': [
        {lat: 35.89, lon: -78.71, desc: 'Begin: Crabtree Valley Mall area'},
        {lat: 35.82, lon: -78.71, desc: 'End: Crabtree Creek overflow'},
        {lat: 35.85, lon: -78.70, desc: 'Crabtree Valley Mall (approx)'},
        {lat: 35.86, lon: -78.68, desc: 'Newton Road near Six Forks Road (approx)'},
        {lat: 35.88, lon: -78.71, desc: 'Leesville Road & Millbrook Road (approx)'}
      ],
      '775032': [{lat: 35.8, lon: -78.61, desc: 'North Raleigh Boulevard near Millbank Street'}],
      '775034': [{lat: 35.79, lon: -78.64, desc: 'Peace Street and Capitol Boulevard'}],
      '775037': [{lat: 35.8148, lon: -78.6198, desc: 'Atlantic Avenue at Hodges Street'}],
      '775029': [{lat: 35.6332, lon: -78.7092, desc: 'Banks Road and Ten Ten Road'}],
      '775031': [{lat: 35.7294, lon: -78.6466, desc: 'Gideon Creek Way near Durham Drive'}],
      '781167': [{lat: 35.8049, lon: -78.623, desc: 'Wake Forest Road near Georgetown Road'}],
      '1029187': [{lat: 35.7864, lon: -78.7353, desc: 'Wolf Creek Circle'}],
      '1173317': [{lat: 35.7794, lon: -78.6435, desc: 'Union Station (S West St & W Martin St)'}],
      '1208861': [{lat: 35.7742, lon: -78.6469, desc: 'Union Station (West St & Martin St)'}],
      '1208432': [{lat: 35.77, lon: -78.73, desc: 'I-440 eastbound (closed)'}]
    }
  },
  houston: {
    outerAOICoords: [
      [-95.95, 29.45],
      [-94.9, 29.45],
      [-94.9, 30.2],
      [-95.95, 30.2],
      [-95.95, 29.45]
    ],
    focusBuffer: 0, // No buffer - use full AOI
    centerZoom: 11,
    floodLocations: {
      '579534': [
        {lat: 30.1143, lon: -95.4547, desc: 'SPRING'},
        {lat: 29.5997, lon: -95.6387, desc: 'HOUSTON HULL ARPT'}
      ],
      '675235_and_1_more': [
        {lat: 29.5897, lon: -95.4473, desc: 'ALMEDA'},
        {lat: 29.7156, lon: -95.2048, desc: 'PASADENA'},
        {lat: 29.7598, lon: -95.3668, desc: 'ENGLEWOOD'},
        {lat: 29.6487, lon: -95.5412, desc: 'MISSOURI CITY'}
      ],
      '710731': [
        {lat: 29.7758, lon: -95.5879, desc: 'HERMOSSEY'},
        {lat: 29.7878, lon: -95.3474, desc: 'ENGLEWOOD'}
      ],
      '710726_and_1_more': [
        {lat: 29.8919, lon: -95.3761, desc: 'LITTLE YORK'},
        {lat: 29.8169, lon: -95.165, desc: 'FAUNA'},
        {lat: 29.7227, lon: -95.465, desc: 'BELLAIRE JCT'},
        {lat: 29.88, lon: -95.4626, desc: 'GORDEN PARK'}
      ],
      '721084_and_5_more': [
        {lat: 29.8067, lon: -95.4204, desc: 'WHITE OAK ACRES'},
        {lat: 29.7525, lon: -95.4228, desc: 'HOUSTON HGTS'},
        {lat: 30.1431, lon: -95.7622, desc: 'TOMBALL'},
        {lat: 30.131, lon: -95.4135, desc: 'SPRING'},
        {lat: 30.0375, lon: -95.4187, desc: 'WESTFIELD'},
        {lat: 29.6896, lon: -95.2072, desc: 'PASADENA (721096)'}
      ],
      '830461_and_1_more': [
        {lat: 29.8976, lon: -95.8261, desc: 'KATY'},
        {lat: 29.6927, lon: -95.8523, desc: 'DELHI'},
        {lat: 29.9508, lon: -95.3076, desc: 'TODD MISSION'},
        {lat: 29.9301, lon: -95.3137, desc: 'TODD MISSION'}
      ],
      '857803_and_4_more': [
        {lat: 29.6666, lon: -95.1575, desc: 'GOLDEN ACRES'},
        {lat: 29.6666, lon: -95.1538, desc: 'GOLDEN ACRES'},
        {lat: 30.0579, lon: -95.1776, desc: 'HUMBLE'},
        {lat: 30.0755, lon: -95.1071, desc: 'HUFFMAN'},
        {lat: 29.963, lon: -95.3391, desc: '(IAH)HOUSTON INTL AR'}
      ],
      '899524': [
        {lat: 29.79, lon: -95.82, desc: 'KATY'},
        {lat: 29.8685, lon: -95.6419, desc: 'HOUSTON LAKESIDE ARP'}
      ],
      '963117': [
        {lat: 29.82, lon: -95.34, desc: 'SETTEGAST'},
        {lat: 29.8231, lon: -95.3407, desc: 'SETTEGAST'}
      ],
      '1004355_and_4_more': [
        {lat: 29.78, lon: -95.54, desc: 'HERMOSSEY'},
        {lat: 29.7881, lon: -95.5383, desc: 'HERMOSSEY'},
        {lat: 29.8228, lon: -95.5298, desc: 'SPRING BRANCH'},
        {lat: 29.8224, lon: -95.5203, desc: 'SPRING BRANCH'},
        {lat: 29.8198, lon: -95.5015, desc: 'SPRING BRANCH'}
      ]
    }
  }
};

// ============================================================================
// EVENT DATA (same as visualize_flood_events.js)
// ============================================================================

var eventsByCity = {
  "raleigh": [
    {
        "id": "755610",
        "label": "Raleigh flood 2018-05-21",
        "event_date": "2018-05-21",
        "noaa_event_ids": "755610",
        "noaa_event_count": "1",
        "sentinel1": {
            "before": {
                "date": "2018-05-10",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20180510T231408_20180510T231433_021849_025BA5_EB89"
            },
            "after": {
                "date": "2018-05-22",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20180522T231409_20180522T231434_022024_026137_6DDC"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2018-05-09",
                "imageId": "COPERNICUS/S2_SR/20180509T155859_20180509T160532_T17SQV",
                "validFraction": 0.768
            },
            "after": null
        },
        "landsat": {
            "before": {
                "date": "2018-05-12",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_016035_20180512",
                "validFraction": 0.99
            },
            "after": null
        }
    },
    {
        "id": "775029_and_1_more",
        "label": "Raleigh flood 2018-07-07 (composite: 2 events)",
        "event_date": "2018-07-07",
        "noaa_event_ids": "775029;775031",
        "noaa_event_count": "2",
        "sentinel1": {
            "before": {
                "date": "2018-06-27",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20180627T231411_20180627T231436_022549_027150_2A0E"
            },
            "after": {
                "date": "2018-07-09",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20180709T231411_20180709T231436_022724_02766D_A8A8"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2018-06-28",
                "imageId": "COPERNICUS/S2_SR/20180628T155819_20180628T160601_T17SQV",
                "validFraction": 0.238
            },
            "after": {
                "date": "2018-07-08",
                "imageId": "COPERNICUS/S2_SR/20180708T155819_20180708T161248_T17SQV",
                "validFraction": 0.769
            }
        },
        "landsat": {
            "before": {
                "date": "2018-06-29",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_016035_20180629",
                "validFraction": 0.709
            },
            "after": {
                "date": "2018-07-08",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_015035_20180708",
                "validFraction": 0.851
            }
        }
    },
    {
        "id": "1029187",
        "label": "Raleigh flood 2022-05-23",
        "event_date": "2022-05-23",
        "noaa_event_ids": "1029187",
        "noaa_event_count": "1",
        "sentinel1": {
            "before": {
                "date": "2022-05-13",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20220513T231430_20220513T231455_043199_0528C5_5077"
            },
            "after": {
                "date": "2022-05-25",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20220525T231430_20220525T231455_043374_052DF9_09E0"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2022-05-20",
                "imageId": "COPERNICUS/S2_SR/20220520T154821_20220520T155606_T17SQA",
                "validFraction": 0.052
            },
            "after": {
                "date": "2022-05-23",
                "imageId": "COPERNICUS/S2_SR/20220523T155831_20220523T160634_T17SQV",
                "validFraction": 0.181
            }
        },
        "landsat": {
            "before": {
                "date": "2022-05-16",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_015035_20220516",
                "validFraction": 0.016
            },
            "after": {
                "date": "2022-05-23",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_016035_20220523",
                "validFraction": 0.309
            }
        }
    },
    {
        "id": "1173317",
        "label": "Raleigh flood 2024-05-25",
        "event_date": "2024-05-25",
        "noaa_event_ids": "1173317",
        "noaa_event_count": "1",
        "sentinel1": {
            "before": {
                "date": "2024-05-14",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20240514T231439_20240514T231504_053874_068C4B_5E79"
            },
            "after": {
                "date": "2024-05-26",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20240526T231440_20240526T231505_054049_069253_4EF3"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2024-05-19",
                "imageId": "COPERNICUS/S2_SR/20240519T154941_20240519T155829_T17SQA",
                "validFraction": 0.0
            },
            "after": null
        },
        "landsat": {
            "before": {
                "date": "2024-05-21",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_015035_20240521",
                "validFraction": 0.828
            },
            "after": null
        }
    },
    {
        "id": "1208432",
        "label": "Raleigh flood 2024-08-04",
        "event_date": "2024-08-04",
        "noaa_event_ids": "1208432",
        "noaa_event_count": "1",
        "sentinel1": {
            "before": {
                "date": "2024-07-13",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20240713T231438_20240713T231503_054749_06AA93_B3A0"
            },
            "after": {
                "date": "2024-08-06",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20240806T231437_20240806T231502_055099_06B6C2_779E"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2024-07-28",
                "imageId": "COPERNICUS/S2_SR/20240728T154941_20240728T160102_T17SQV",
                "validFraction": 0.662
            },
            "after": null
        },
        "landsat": {
            "before": {
                "date": "2024-07-31",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_016035_20240731",
                "validFraction": 1.0
            },
            "after": null
        }
    }
  ],
  "houston": [
    {
        "id": "579534",
        "label": "Houston flood 2015-05-30",
        "event_date": "2015-05-30",
        "noaa_event_ids": "579534",
        "noaa_event_count": "1",
        "sentinel1": {
            "before": {
                "date": "2015-05-07",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20150507T122236_20150507T122305_005815_0077A7_ABD7"
            },
            "after": {
                "date": "2015-05-31",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20150531T122237_20150531T122307_006165_008054_86FA"
            }
        },
        "sentinel2": {
            "before": null,
            "after": null
        },
        "landsat": {
            "before": {
                "date": "2015-05-26",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_026039_20150526",
                "validFraction": 0.201
            },
            "after": null
        }
    },
    {
        "id": "675235_and_1_more",
        "label": "Houston flood 2017-01-18 (composite: 2 events)",
        "event_date": "2017-01-18",
        "noaa_event_ids": "675235;675098",
        "noaa_event_count": "2",
        "sentinel1": {
            "before": {
                "date": "2017-01-08",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20170108T001813_20170108T001842_014733_017FB8_BB4E"
            },
            "after": {
                "date": "2017-01-20",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20170120T001812_20170120T001841_014908_018538_5822"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2017-01-07",
                "imageId": "COPERNICUS/S2_SR/20170107T170701_20170107T170831_T15RTN",
                "validFraction": 0.676
            },
            "after": null
        },
        "landsat": {
            "before": {
                "date": "2017-01-16",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_025039_20170116",
                "validFraction": 0.677
            },
            "after": null
        }
    },
    {
        "id": "710731",
        "label": "Houston flood 2017-06-04",
        "event_date": "2017-06-04",
        "noaa_event_ids": "710731",
        "noaa_event_count": "1",
        "sentinel1": {
            "before": {
                "date": "2017-05-25",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20170525T002614_20170525T002639_016731_01BC9B_8DEE"
            },
            "after": {
                "date": "2017-06-06",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20170606T002615_20170606T002640_016906_01C211_F481"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2017-05-24",
                "imageId": "COPERNICUS/S2_SR/20170524T170531_20170524T170526_T15RTN",
                "validFraction": 0.559
            },
            "after": null
        },
        "landsat": {
            "before": {
                "date": "2017-05-24",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_025039_20170524",
                "validFraction": 0.999
            },
            "after": null
        }
    },
    {
        "id": "710726_and_1_more",
        "label": "Houston flood 2017-06-24 (composite: 2 events)",
        "event_date": "2017-06-24",
        "noaa_event_ids": "710726;710727",
        "noaa_event_count": "2",
        "sentinel1": {
            "before": {
                "date": "2017-06-13",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20170613T001820_20170613T001845_017008_01C531_1EE5"
            },
            "after": {
                "date": "2017-06-25",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20170625T001820_20170625T001845_017183_01CA88_6F42"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2017-06-16",
                "imageId": "COPERNICUS/S2_SR/20170616T170311_20170616T171505_T15RTN",
                "validFraction": 0.476
            },
            "after": null
        },
        "landsat": {
            "before": {
                "date": "2017-06-16",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_026039_20170616",
                "validFraction": 0.176
            },
            "after": {
                "date": "2017-06-25",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_025039_20170625",
                "validFraction": 0.303
            }
        }
    },
    {
        "id": "721084_and_5_more",
        "label": "Houston flood 2017-08-27 (composite: 6 events)",
        "event_date": "2017-08-27",
        "noaa_event_ids": "721084;721085;721091;721096;721101;721136",
        "noaa_event_count": "6",
        "sentinel1": {
            "before": {
                "date": "2017-08-05",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20170805T002619_20170805T002644_017781_01DCB4_1716"
            },
            "after": {
                "date": "2017-08-29",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20170829T002620_20170829T002645_018131_01E74D_D734"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2017-08-15",
                "imageId": "COPERNICUS/S2_SR/20170815T165851_20170815T171519_T15RTP",
                "validFraction": 0.458
            },
            "after": null
        },
        "landsat": {
            "before": {
                "date": "2017-08-19",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_026039_20170819",
                "validFraction": 0.149
            },
            "after": null
        }
    },
    {
        "id": "830461_and_1_more",
        "label": "Houston flood 2019-05-09 (composite: 2 events)",
        "event_date": "2019-05-09",
        "noaa_event_ids": "830461;830464",
        "noaa_event_count": "2",
        "sentinel1": {
            "before": {
                "date": "2019-04-16",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20190416T001829_20190416T001854_026808_030341_09F6"
            },
            "after": {
                "date": "2019-05-10",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20190510T001830_20190510T001855_027158_030FB5_A959"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2019-05-04",
                "imageId": "COPERNICUS/S2_SR/20190504T164901_20190504T170412_T15RTN",
                "validFraction": 0.439
            },
            "after": {
                "date": "2019-05-09",
                "imageId": "COPERNICUS/S2_SR/20190509T164849_20190509T170403_T15RTP",
                "validFraction": 0.003
            }
        },
        "landsat": {
            "before": {
                "date": "2019-04-28",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_025039_20190428",
                "validFraction": 0.362
            },
            "after": null
        }
    },
    {
        "id": "857803_and_4_more",
        "label": "Houston flood 2019-09-18 (composite: 5 events)",
        "event_date": "2019-09-18",
        "noaa_event_ids": "857803;858108;858116;858117;869176",
        "noaa_event_count": "5",
        "sentinel1": {
            "before": {
                "date": "2019-09-07",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20190907T001837_20190907T001902_028908_0346F0_99F7"
            },
            "after": {
                "date": "2019-09-19",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20190919T001837_20190919T001902_029083_034D00_7C4E"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2019-09-14",
                "imageId": "COPERNICUS/S2_SR/20190914T165921_20190914T170704_T15RTN",
                "validFraction": 0.673
            },
            "after": null
        },
        "landsat": {
            "before": {
                "date": "2019-09-10",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_026039_20190910",
                "validFraction": 0.135
            },
            "after": null
        }
    },
    {
        "id": "899524",
        "label": "Houston flood 2020-06-25",
        "event_date": "2020-06-25",
        "noaa_event_ids": "899524",
        "noaa_event_count": "1",
        "sentinel1": {
            "before": {
                "date": "2020-06-14",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20200614T002635_20200614T002700_033006_03D2B2_9749"
            },
            "after": {
                "date": "2020-06-26",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20200626T002636_20200626T002701_033181_03D804_3ED2"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2020-06-17",
                "imageId": "COPERNICUS/S2_SR/20200617T164901_20200617T170013_T15RTN",
                "validFraction": 0.391
            },
            "after": null
        },
        "landsat": {
            "before": {
                "date": "2020-06-17",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_025039_20200617",
                "validFraction": 0.805
            },
            "after": null
        }
    },
    {
        "id": "963117",
        "label": "Houston flood 2021-06-21",
        "event_date": "2021-06-21",
        "noaa_event_ids": "963117",
        "noaa_event_count": "1",
        "sentinel1": {
            "before": {
                "date": "2021-06-09",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20210609T002640_20210609T002705_038256_0483BB_7601"
            },
            "after": {
                "date": "2021-06-21",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20210621T002641_20210621T002706_038431_0488F1_75AA"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2021-06-17",
                "imageId": "COPERNICUS/S2_SR/20210617T164839_20210617T170159_T15RTP",
                "validFraction": 0.407
            },
            "after": {
                "date": "2021-06-22",
                "imageId": "COPERNICUS/S2_SR/20210622T164901_20210622T165949_T15RTP",
                "validFraction": 0.208
            }
        },
        "landsat": {
            "before": {
                "date": "2021-06-11",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_026039_20210611",
                "validFraction": 0.183
            },
            "after": null
        }
    },
    {
        "id": "1004355_and_4_more",
        "label": "Houston flood 2022-01-09 (composite: 5 events)",
        "event_date": "2022-01-09",
        "noaa_event_ids": "1004355;1004356;1004366;1004373;1004376",
        "noaa_event_count": "5",
        "sentinel1": {
            "before": {
                "date": "2021-12-30",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20211230T002644_20211230T002709_041231_04E66D_5F0B"
            },
            "after": {
                "date": "2022-01-11",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20220111T002644_20220111T002709_041406_04EC59_F1CD"
            }
        },
        "sentinel2": {
            "before": {
                "date": "2022-01-03",
                "imageId": "COPERNICUS/S2_SR/20220103T165709_20220103T170107_T15RTN",
                "validFraction": 0.542
            },
            "after": null
        },
        "landsat": {
            "before": {
                "date": "2022-01-05",
                "imageId": "LANDSAT/LC08/C02/T1_L2/LC08_026039_20220105",
                "validFraction": 0.287
            },
            "after": null
        }
    },
    {
        "id": "control_2024-10-15",
        "label": "Houston CONTROL (no flood) 2024-10-15",
        "event_date": "2024-10-15",
        "noaa_event_ids": "none",
        "noaa_event_count": "0",
        "sentinel1": {
            "before": {
                "date": "2024-10-03",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20241003T002718_20241003T002743_055931_06D696_ACEF"
            },
            "after": {
                "date": "2024-10-15",
                "imageId": "COPERNICUS/S1_GRD/S1A_IW_GRDH_1SDV_20241015T002719_20241015T002744_056106_06DD72_7C83"
            }
        },
        "sentinel2": {
            "before": null,
            "after": null
        },
        "landsat": {
            "before": null,
            "after": null
        }
    }
  ]
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

function buildFocusAOI(cityKey) {
  var cfg = cityConfig[cityKey];
  var outer = ee.Geometry.Polygon([cfg.outerAOICoords]);
  if (cfg.focusBuffer && cfg.focusBuffer !== 0) {
    return outer.buffer(cfg.focusBuffer).bounds();
  }
  return outer;
}

function toDbSafe(img, band) {
  // Sentinel-1 GRD data in Earth Engine is already in dB scale
  return ee.Image(img).select(band);
}

function loadSentinel1(imageId, eventDate) {
  if (!imageId) return null;
  
  var specificImage = ee.Image(imageId);
  
  if (eventDate) {
    var eventDateObj = ee.Date(eventDate);
    var startDate = eventDateObj.advance(-1, 'day');
    var endDate = eventDateObj.advance(1, 'day');
    
    var s1Collection = ee.ImageCollection('COPERNICUS/S1_GRD')
      .filterBounds(focusAOI)
      .filterDate(startDate, endDate)
      .filter(ee.Filter.listContains('system:band_names', 'VV'));
    
    var count = s1Collection.size();
    
    var result = ee.Algorithms.If(
      count.gt(1),
      s1Collection.mosaic(),
      specificImage
    );
    
    return ee.Image(result);
  }
  return specificImage;
}

function loadSentinel1MultiImageBaseline(imageId, eventDate, beforeDate) {
  if (!imageId || !eventDate || !beforeDate) {
    return loadSentinel1(imageId, eventDate);
  }
  
  var referenceImage = ee.Image(imageId);
  var referenceOrbitPass = referenceImage.get('orbitProperties_pass');
  var referenceOrbitNumber = referenceImage.get('relativeOrbitNumber_start');
  
  var eventDateObj = ee.Date(eventDate);
  var beforeDateObj = ee.Date(beforeDate);
  
  var searchStartDate = beforeDateObj.advance(-multiImageDaysBefore, 'day');
  var searchEndDate = beforeDateObj.advance(1, 'day');
  
  var preEventCollection = ee.ImageCollection('COPERNICUS/S1_GRD')
    .filterBounds(focusAOI)
    .filterDate(searchStartDate, searchEndDate)
    .filter(ee.Filter.listContains('system:band_names', 'VV'))
    .filter(ee.Filter.eq('orbitProperties_pass', referenceOrbitPass))
    .filter(ee.Filter.eq('relativeOrbitNumber_start', referenceOrbitNumber))
    .sort('system:time_start', false)
    .limit(multiImageMaxCount);
  
  var count = preEventCollection.size();
  
  var result = ee.Algorithms.If(
    count.gt(1),
    preEventCollection.mean(),
    ee.Algorithms.If(
      count.eq(1),
      preEventCollection.first(),
      loadSentinel1(imageId, eventDate)
    )
  );
  
  return ee.Image(result);
}

// Generate flood mask for a single event
function generateFloodMask(eventInfo) {
  var beforeImageId = eventInfo.sentinel1.before && eventInfo.sentinel1.before.imageId;
  var beforeDate = eventInfo.sentinel1.before && eventInfo.sentinel1.before.date;
  var afterImageId = eventInfo.sentinel1.after && eventInfo.sentinel1.after.imageId;
  var afterDate = eventInfo.sentinel1.after && eventInfo.sentinel1.after.date;
  
  if (!beforeImageId || !afterImageId) {
    return null;
  }
  
  // Load images
  var before = useMultiImageBaseline 
    ? loadSentinel1MultiImageBaseline(beforeImageId, eventInfo.event_date, beforeDate)
    : loadSentinel1(beforeImageId, beforeDate);
  var after = loadSentinel1(afterImageId, afterDate);
  
  if (!before || !after) {
    return null;
  }
  
  // Clip to AOI
  before = before.clip(focusAOI);
  after = after.clip(focusAOI);
  
  // Urban mask
  var worldCover = ee.Image('ESA/WorldCover/v200/2021').select('Map').rename('landcover');
  var worldCoverBuilt = worldCover.eq(FLOOD_DETECTION_CONFIG.worldCoverBuiltClass);
  var nlcdImpervious = ee.Image('USGS/NLCD_RELEASES/2021_REL/NLCD/2021')
    .select('impervious')
    .divide(100);
  var nlcdImperviousMask = nlcdImpervious
    .updateMask(nlcdImpervious.mask())
    .gte(FLOOD_DETECTION_CONFIG.nlcdImperviousThreshold);
  var urbanMask = worldCoverBuilt.or(nlcdImperviousMask);
  
  // Permanent water mask
  var jrcWater = ee.Image('JRC/GSW1_4/GlobalSurfaceWater').select('occurrence');
  var permanentWater = jrcWater.gte(FLOOD_DETECTION_CONFIG.jrcWaterOccurrenceThreshold).unmask(0).rename('perm_water');
  
  // Calculate change detection
  var beforeVV = toDbSafe(before, 'VV');
  var afterVV = toDbSafe(after, 'VV');
  
  // Smooth and calculate change
  var beforeVVSmoothed = beforeVV.focal_mean(FLOOD_DETECTION_CONFIG.smoothRadius, 'circle', 'meters');
  var afterVVSmoothed = afterVV.focal_mean(FLOOD_DETECTION_CONFIG.smoothRadius, 'circle', 'meters');
  var vvChangeSmoothed = afterVVSmoothed.subtract(beforeVVSmoothed);
  
  // Threshold: use fixed or adaptive (percentile of VV change over AOI, clamped)
  var thresholdVvVh = ee.Number(FLOOD_DETECTION_CONFIG.vvVhThreshold);
  var thresholdVvOnly = ee.Number(FLOOD_DETECTION_CONFIG.vvOnlyThreshold);
  
  // Check if VH exists
  var beforeBands = before.bandNames();
  var afterBands = after.bandNames();
  var beforeHasVH = beforeBands.filter(ee.Filter.eq('item', 'VH')).size().gt(0);
  var afterHasVH = afterBands.filter(ee.Filter.eq('item', 'VH')).size().gt(0);
  var bothHaveVH = beforeHasVH.and(afterHasVH);
  
  // Create VV mask
  var vvMask = vvChangeSmoothed.lt(thresholdVvVh).rename('flood');
  
  // Create VH mask if available
  var vhChangeSmoothed = ee.Algorithms.If(
    bothHaveVH,
    ee.Image(toDbSafe(after, 'VH'))
      .focal_mean(FLOOD_DETECTION_CONFIG.smoothRadius, 'circle', 'meters')
      .subtract(ee.Image(toDbSafe(before, 'VH')).focal_mean(FLOOD_DETECTION_CONFIG.smoothRadius, 'circle', 'meters')),
    ee.Image.constant(0)
  );
  
  var vhMask = ee.Algorithms.If(
    bothHaveVH,
    ee.Image(vhChangeSmoothed).lt(thresholdVvVh).rename('flood'),
    ee.Image.constant(0).mask(ee.Image.constant(0))
  );
  
  // Combine masks
  var floodMask = ee.Image(ee.Algorithms.If(
    bothHaveVH,
    vvMask.multiply(ee.Image(vhMask)),
    vvChangeSmoothed.lt(thresholdVvOnly)
  )).rename('flood');
  
  // Pre-urban mask for NOAA validation (threshold + permanent water + speckle; no urban)
  var floodMaskPreUrban = floodMask
    .updateMask(permanentWater.not())
    .clip(focusAOI);
  floodMaskPreUrban = floodMaskPreUrban.updateMask(
    floodMaskPreUrban.connectedPixelCount(FLOOD_DETECTION_CONFIG.connectedNeighborhood, true)
      .gte(FLOOD_DETECTION_CONFIG.minConnectedPixels)
  );
  
  // Apply urban and permanent water for hotspot mask
  floodMask = floodMask
    .updateMask(urbanMask)
    .updateMask(permanentWater.not())
    .clip(focusAOI);
  
  // Remove small speckle
  floodMask = floodMask.updateMask(
    floodMask.connectedPixelCount(FLOOD_DETECTION_CONFIG.connectedNeighborhood, true)
      .gte(FLOOD_DETECTION_CONFIG.minConnectedPixels)
  );
  
  return { mask: floodMask, maskPreUrban: floodMaskPreUrban };
}

// Same as generateFloodMask but uses scene-adaptive threshold (percentile of VV change, clamped)
function generateFloodMaskAdaptive(eventInfo) {
  var beforeImageId = eventInfo.sentinel1.before && eventInfo.sentinel1.before.imageId;
  var beforeDate = eventInfo.sentinel1.before && eventInfo.sentinel1.before.date;
  var afterImageId = eventInfo.sentinel1.after && eventInfo.sentinel1.after.imageId;
  var afterDate = eventInfo.sentinel1.after && eventInfo.sentinel1.after.date;
  
  if (!beforeImageId || !afterImageId) {
    return null;
  }
  
  var before = useMultiImageBaseline 
    ? loadSentinel1MultiImageBaseline(beforeImageId, eventInfo.event_date, beforeDate)
    : loadSentinel1(beforeImageId, beforeDate);
  var after = loadSentinel1(afterImageId, afterDate);
  
  if (!before || !after) {
    return null;
  }
  
  before = before.clip(focusAOI);
  after = after.clip(focusAOI);
  
  var worldCover = ee.Image('ESA/WorldCover/v200/2021').select('Map').rename('landcover');
  var worldCoverBuilt = worldCover.eq(FLOOD_DETECTION_CONFIG.worldCoverBuiltClass);
  var nlcdImpervious = ee.Image('USGS/NLCD_RELEASES/2021_REL/NLCD/2021')
    .select('impervious')
    .divide(100);
  var nlcdImperviousMask = nlcdImpervious
    .updateMask(nlcdImpervious.mask())
    .gte(FLOOD_DETECTION_CONFIG.nlcdImperviousThreshold);
  var urbanMask = worldCoverBuilt.or(nlcdImperviousMask);
  
  var jrcWater = ee.Image('JRC/GSW1_4/GlobalSurfaceWater').select('occurrence');
  var permanentWater = jrcWater.gte(FLOOD_DETECTION_CONFIG.jrcWaterOccurrenceThreshold).unmask(0).rename('perm_water');
  
  var beforeVV = toDbSafe(before, 'VV');
  var afterVV = toDbSafe(after, 'VV');
  var beforeVVSmoothed = beforeVV.focal_mean(FLOOD_DETECTION_CONFIG.smoothRadius, 'circle', 'meters');
  var afterVVSmoothed = afterVV.focal_mean(FLOOD_DETECTION_CONFIG.smoothRadius, 'circle', 'meters');
  var vvChangeSmoothed = afterVVSmoothed.subtract(beforeVVSmoothed);
  
  var vvChangeForReduce = vvChangeSmoothed.rename('change');
  var percentileResult = vvChangeForReduce.reduceRegion({
    reducer: ee.Reducer.percentile([FLOOD_DETECTION_CONFIG.adaptivePercentile], ['change']),
    geometry: focusAOI,
    scale: 100,
    bestEffort: true
  });
  var adaptiveThreshold = ee.Number(percentileResult.get('change'))
    .max(FLOOD_DETECTION_CONFIG.adaptiveThresholdMin)
    .min(FLOOD_DETECTION_CONFIG.adaptiveThresholdMax);
  var thresholdVvVh = adaptiveThreshold;
  var thresholdVvOnly = adaptiveThreshold;
  
  var beforeBands = before.bandNames();
  var afterBands = after.bandNames();
  var beforeHasVH = beforeBands.filter(ee.Filter.eq('item', 'VH')).size().gt(0);
  var afterHasVH = afterBands.filter(ee.Filter.eq('item', 'VH')).size().gt(0);
  var bothHaveVH = beforeHasVH.and(afterHasVH);
  
  var vvMask = vvChangeSmoothed.lt(thresholdVvVh).rename('flood');
  var vhChangeSmoothed = ee.Algorithms.If(
    bothHaveVH,
    ee.Image(toDbSafe(after, 'VH'))
      .focal_mean(FLOOD_DETECTION_CONFIG.smoothRadius, 'circle', 'meters')
      .subtract(ee.Image(toDbSafe(before, 'VH')).focal_mean(FLOOD_DETECTION_CONFIG.smoothRadius, 'circle', 'meters')),
    ee.Image.constant(0)
  );
  var vhMask = ee.Algorithms.If(
    bothHaveVH,
    ee.Image(vhChangeSmoothed).lt(thresholdVvVh).rename('flood'),
    ee.Image.constant(0).mask(ee.Image.constant(0))
  );
  var floodMask = ee.Image(ee.Algorithms.If(
    bothHaveVH,
    vvMask.multiply(ee.Image(vhMask)),
    vvChangeSmoothed.lt(thresholdVvOnly)
  )).rename('flood');
  
  var floodMaskPreUrban = floodMask
    .updateMask(permanentWater.not())
    .clip(focusAOI);
  floodMaskPreUrban = floodMaskPreUrban.updateMask(
    floodMaskPreUrban.connectedPixelCount(FLOOD_DETECTION_CONFIG.connectedNeighborhood, true)
      .gte(FLOOD_DETECTION_CONFIG.minConnectedPixels)
  );
  
  floodMask = floodMask
    .updateMask(urbanMask)
    .updateMask(permanentWater.not())
    .clip(focusAOI);
  floodMask = floodMask.updateMask(
    floodMask.connectedPixelCount(FLOOD_DETECTION_CONFIG.connectedNeighborhood, true)
      .gte(FLOOD_DETECTION_CONFIG.minConnectedPixels)
  );
  return { mask: floodMask, maskPreUrban: floodMaskPreUrban };
}

// Get NOAA validation locations for an event (same logic as visualize_flood_events.js)
function getValidationLocations(eventInfo) {
  var floodLocations = cityConfig[selectedCity].floodLocations || {};
  var eventId = eventInfo.id;
  var noaaIds = eventInfo.noaa_event_ids || '';
  var locations = [];
  if (floodLocations[eventId]) {
    locations = floodLocations[eventId];
  } else if (noaaIds.indexOf(';') >= 0) {
    noaaIds.split(';').forEach(function(id) {
      id = id.trim();
      if (floodLocations[id]) {
        locations = locations.concat(floodLocations[id]);
      }
    });
  } else {
    var checkId = noaaIds.trim();
    if (floodLocations[checkId]) {
      locations = floodLocations[checkId];
    }
  }
  return locations;
}

// ============================================================================
// MAIN PROCESSING
// ============================================================================

var focusAOI = buildFocusAOI(selectedCity);
Map.clear();
Map.centerObject(focusAOI, cityConfig[selectedCity].centerZoom);

var allEvents = eventsByCity[selectedCity];
if (!allEvents || allEvents.length === 0) {
  throw new Error('No events found for city: ' + selectedCity);
}

// Filter out control events (noaa_event_ids === 'none' or noaa_event_count === '0')
var floodEvents = allEvents.filter(function(event) {
  return event.noaa_event_ids !== 'none' && parseInt(event.noaa_event_count) > 0;
});

print('City:', selectedCity);
print('Total events:', allEvents.length);
print('Flood events (excluding control):', floodEvents.length);
print('Threshold mode:', useAdaptiveThreshold ? 'adaptive (percentile, clamped)' : 'fixed dB');

// Generate flood masks for all events (fixed or adaptive threshold per flag)
var maskList = [];
var preUrbanMaskList = [];
var eventIndexForMask = [];
for (var i = 0; i < floodEvents.length; i++) {
  var result = useAdaptiveThreshold
    ? generateFloodMaskAdaptive(floodEvents[i])
    : generateFloodMask(floodEvents[i]);
  if (result !== null) {
    maskList.push(result.mask);
    preUrbanMaskList.push(result.maskPreUrban);
    eventIndexForMask.push(i);
  }
}

print('Events with valid flood masks:', maskList.length);
print('');
print('=== INDEPENDENT VALIDATION (2015-2025, docs/validation_independence.md) ===');
print('Map: ever-flooded union from M SAR events (' + maskList.length + ' composites)');
print('Threshold train composites: ' + (THRESHOLD_TRAIN_COMPOSITE_IDS[selectedCity] || []).join(', '));
print('Locked thresholds: VV+VH=' + FLOOD_DETECTION_CONFIG.vvVhThreshold + ' dB, VV-only=' + FLOOD_DETECTION_CONFIG.vvOnlyThreshold + ' dB');
print('Test: N-M NOAA points (no SAR) vs ever-flooded map — generous, independent reference');
print('');

// Validation buffer distances (meters) for independent N-M recall
var VALIDATION_BUFFERS_M = [100, 250, 500, 1000];
var everFloodedMap = ee.ImageCollection.fromImages(preUrbanMaskList).sum().gte(1).rename('flood');
var aggregateValidationMask = everFloodedMap;

function bufferedRecallOnMap(mapImage, pointsFC, bufferM) {
  var pointsInAOI = pointsFC.filterBounds(focusAOI);
  // Dilate flood mask by bufferM so point samples == "flood within B meters"
  var dilated = mapImage.unmask(0).focal_max({radius: bufferM, units: 'meters'});
  var sampled = dilated.sampleRegions({
    collection: pointsInAOI,
    properties: [],
    scale: 100,
    tileScale: 4,
    geometries: false
  });
  var withHits = sampled.map(function(f) {
    return f.set('hit', ee.Number(f.get('flood')).gte(1).toInt());
  });
  var total = withHits.size();
  var hits = withHits.aggregate_sum('hit');
  return ee.Dictionary({total: total, hits: hits});
}

function recallDictForBuffers(mapImage, pointsFC, buffersM) {
  var keys = [];
  var vals = [];
  for (var i = 0; i < buffersM.length; i++) {
    var b = buffersM[i];
    var r = bufferedRecallOnMap(mapImage, pointsFC, b);
    keys.push('total_' + b);
    vals.push(r.get('total'));
    keys.push('hits_' + b);
    vals.push(r.get('hits'));
  }
  return ee.Dictionary.fromLists(keys, vals);
}

function printRecallFromDict(s, buffersM, title) {
  print(title);
  if (!s) {
    print('  ERROR: evaluation failed — check Tasks tab for details.');
    print('');
    return;
  }
  var any = false;
  for (var i = 0; i < buffersM.length; i++) {
    var b = buffersM[i];
    var t = s['total_' + b] || 0;
    var h = s['hits_' + b] || 0;
    if (t > 0) {
      any = true;
      var pad = b < 1000 ? '  ' : ' ';
      print('  ' + b + ' m buffered recall:' + pad + h + '/' + t + ' = ' + Math.round(100 * h / t) + '%');
    }
  }
  if (!any) {
    print('  No points inside AOI.');
  }
  print('');
}

// Independent test points (N-M): from independent_validation_locations.js
var independentLocs = (typeof independentValidationLocations !== 'undefined' &&
  independentValidationLocations[selectedCity])
  ? independentValidationLocations[selectedCity]
  : [];

if (independentLocs.length === 0) {
  print('WARNING: Load independent_validation_locations.js in this GEE script for N-M validation.');
  print('  Run: python3 code/validation/build_independent_validation.py');
  print('');
} else {
  var independentFC = ee.FeatureCollection(independentLocs.map(function(loc) {
    return ee.Feature(ee.Geometry.Point([loc.lon, loc.lat]), {
      eventId: loc.eventId,
      desc: loc.desc
    });
  }));
  var indepRecall = recallDictForBuffers(everFloodedMap, independentFC, VALIDATION_BUFFERS_M);
  indepRecall.set('nPoints', independentFC.size()).evaluate(
    function(s) {
      var n = (s && s.nPoints) || 0;
      printRecallFromDict(
        s,
        VALIDATION_BUFFERS_M,
        'HEADLINE — independent N-M NOAA test (' + n + ' points, no SAR):'
      );
    },
    function(err) {
      print('HEADLINE — independent N-M NOAA test: evaluation failed');
      print('  ' + err);
      print('');
    }
  );
}

// Random-point spatial null (#14): same buffered hit rate on random AOI locations
var RANDOM_BASELINE_N = 500;
var RANDOM_BASELINE_SEED = 42;
var randomBaselineFC = ee.FeatureCollection.randomPoints({
  region: focusAOI,
  points: RANDOM_BASELINE_N,
  seed: RANDOM_BASELINE_SEED
});
var randomRecall = recallDictForBuffers(everFloodedMap, randomBaselineFC, VALIDATION_BUFFERS_M);
randomRecall.evaluate(
  function(s) {
    printRecallFromDict(
      s,
      VALIDATION_BUFFERS_M,
      'BASELINE — random points in AOI (n=' + RANDOM_BASELINE_N + ', seed=' +
        RANDOM_BASELINE_SEED + ', reviewer #14):'
    );
  },
  function(err) {
    print('BASELINE — random points in AOI: evaluation failed');
    print('  ' + err);
    print('');
  }
);

// Diagnostic: M-event NOAA points (used in map) — not independent, do not use as headline
var mEventPoints = ee.FeatureCollection([]);
for (var m = 0; m < preUrbanMaskList.length; m++) {
  var idxM = eventIndexForMask[m];
  var evM = floodEvents[idxM];
  var locsM = getValidationLocations(evM);
  mEventPoints = mEventPoints.merge(ee.FeatureCollection(locsM.map(function(loc) {
    return ee.Feature(ee.Geometry.Point([loc.lon, loc.lat]));
  })));
}
mEventPoints = mEventPoints.filterBounds(focusAOI);
var mRecall = recallDictForBuffers(everFloodedMap, mEventPoints, VALIDATION_BUFFERS_M);
mRecall.evaluate(
  function(s) {
    if (s && (s['total_500'] || 0) > 0) {
      printRecallFromDict(s, VALIDATION_BUFFERS_M, 'DIAGNOSTIC — M-event NOAA points (circular, not headline):');
    }
  },
  function(err) {
    print('DIAGNOSTIC — M-event NOAA points: evaluation failed');
    print('  ' + err);
    print('');
  }
);

// Aggregate masks by summing (each mask is 1 for flood, 0 for no flood)
// Result: frequency map showing how many events detected flooding at each pixel
var frequencyMap = ee.ImageCollection.fromImages(maskList).sum().rename('frequency');

// Apply discrete color mapping
// 0 = transparent (masked), 1 = orange, 2-3 = red, 4+ = dark red
// Use expression to map frequency values to color indices
var hotspotMap = frequencyMap.expression(
  '(freq == 0) ? 0 : ' +  // 0 = transparent (will be masked)
  '(freq == 1) ? 1 : ' +  // 1 = orange
  '(freq >= 2 && freq <= 3) ? 2 : ' +  // 2-3 = red
  '(freq >= 4) ? 3 : 0',  // 4+ = dark red
  {freq: frequencyMap}
).rename('hotspot_class');

// Mask out zeros (no detections)
hotspotMap = hotspotMap.updateMask(hotspotMap.gt(0));

// Color palette: [orange, red, dark red]
var hotspotPalette = ['FF9800', 'FF5252', 'D32F2F'];

// Add hotspot map to map
Map.addLayer(
  hotspotMap,
  {
    min: 1,
    max: 3,
    palette: hotspotPalette,
    opacity: 0.7
  },
  'Flood Hotspot Map (' + selectedCity + ')'
);

// Add AOI (just box outline — line only, no fill)
var aoiOutline = ee.Geometry.LineString(focusAOI.coordinates().get(0));
Map.addLayer(aoiOutline, {color: 'red'}, 'AOI', true);

// Print statistics
var maxFrequency = frequencyMap.reduceRegion({
  reducer: ee.Reducer.max(),
  geometry: focusAOI,
  scale: 100,
  bestEffort: true
}).get('frequency');

print('Hotspot Statistics:');
print('  Events aggregated:', maskList.length);
print('  Max frequency (events detecting flood at same pixel):', maxFrequency);

// Calculate area statistics
var frequencyStats = frequencyMap.reduceRegion({
  reducer: ee.Reducer.histogram().combine({
    reducer2: ee.Reducer.count(),
    sharedInputs: true
  }),
  geometry: focusAOI,
  scale: 100,
  bestEffort: true
});

print('Frequency distribution:', frequencyStats);

